/** Platform-only states. No fabricated projects, progress or infrastructure. */
export interface Health {worker:string;canConvert:boolean;authRequired:boolean;deployment?:string;storage?:string;message?:string;queueDepth?:number;activeJobs?:number}
const esc=(x:unknown)=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function connectionBanner(health:Health, auth:boolean):string {
  if(health.canConvert&&!auth)return '';
  return `<aside class="connection-banner" role="status"><span class="connection-dot"></span><p>${auth?'Sign in to your private workspace.':esc(health.message||'The conversion service is not connected yet. No jobs can run until it is connected.')}</p><a data-route="${auth?'/login':'/settings'}" href="${auth?'/login':'/settings'}">${auth?'Sign in':'Connection details'} <span aria-hidden="true">↗</span></a></aside>`;
}
export function settingsView(health:Health,signedIn:boolean):string {
  return `<section class="page-heading"><div><div class="eyebrow">WORKSPACE SETTINGS</div><h1>Your workspace.<br>Every part accounted for.</h1><p>Live service status, access and storage. Not a simulated dashboard.</p></div><button class="secondary" id="refresh-health">Refresh status ↻</button></section>
  <section class="service-grid" aria-label="Service status">
    <article><span class="service-label">01 / WEB APPLICATION</span><h2>Studio</h2><strong class="service-value">Online</strong><p>${health.deployment==='gateway'?'Hosted on Vercel. Pages, routes and the WebGL shader are served here.':'Served by the persistent application host.'}</p></article>
    <article><span class="service-label">02 / CONVERSION ENGINE</span><h2>Browser worker</h2><strong class="service-value ${health.canConvert?'':'unavailable'}">${health.canConvert?'Connected':health.worker==='unconfigured'?'Not connected':'Offline'}</strong><p>${esc(health.message||'Waiting for the browser service.')}</p></article>
    <article><span class="service-label">03 / PROJECT STORAGE</span><h2>Persistence</h2><strong class="service-value ${health.storage==='not-connected'?'unavailable':''}">${health.storage==='persistent-volume'?'Persistent volume':health.storage==='local-disk'?'Local disk':'Not connected'}</strong><p>Project records, revision history and export files belong on the worker’s durable volume, not temporary Vercel storage.</p></article>
  </section>
  <section class="settings-panel"><div><div class="eyebrow">PRIVATE WORKSPACE</div><h2>Access that survives a refresh.</h2><p>${signedIn?'You are signed in. Your access key is not stored in the browser.':'Sign in with the access key configured on your conversion service. Your session uses an HTTP-only cookie.'}</p></div><button class="secondary" id="${signedIn?'logout-workspace':'connect-workspace'}" ${!signedIn&&!health.canConvert?'disabled':''}>${signedIn?'Sign out':'Sign in'}</button></section>
  ${health.canConvert?'':`<section class="setup-guide"><div class="eyebrow">DEPLOYMENT CONNECTION REQUIRED</div><h2>The web app is here. The worker still needs a host.</h2><p>The repository includes the persistent service, durable queue, session authentication and Railway configuration. Connect Railway to deploy it, mount its data volume at <code>/data</code>, then set the Vercel variable <code>FRAMEPORT_WORKER_ORIGIN</code> to its HTTPS origin.</p><p>The hosted app deliberately refuses conversions while this service is missing. It does not create temporary projects or pretend a browser is connected.</p><a data-route="/docs" href="/docs" class="secondary">Read the implementation guide ↗</a></section>`}`;
}
export function loginView(error='', ready=true):string {
  return `<section class="login-layout"><div class="eyebrow">YOUR PRIVATE WORKSPACE</div><h1>Pick up where<br>you left off.</h1><p>Sign in once. Your projects and session remain available when you refresh.</p><form id="platform-login"><label for="login-key">Workspace access key</label><input id="login-key" type="password" autocomplete="current-password" required maxlength="256" ${ready?'':'disabled'}><p class="form-error" role="alert">${esc(error)}</p><button class="primary" type="submit" ${ready?'':'disabled'}>Open workspace ↗</button></form>${ready?'':'<p>The conversion service is not connected. <a data-route="/settings" href="/settings">View connection details.</a></p>'}<p class="privacy-copy">HTTP-only session. No credentials in local storage.</p></section>`;
}
export function problemView(message:string,kind:string):string {
  return `<section class="platform-empty"><div class="eyebrow">${kind==='notfound'?'PROJECT NOT FOUND':'WORKSPACE UNAVAILABLE'}</div><h1>${kind==='notfound'?'That page is not here.':'Your work has not disappeared.'}</h1><p>${esc(message)}</p><div><a href="/projects" data-route="/projects" class="secondary">Back to projects</a><a href="/settings" data-route="/settings" class="secondary">Service status</a><button id="retry-route" class="primary">Try again</button></div></section>`;
}
export function exportView(job:{revision:number;report:{pages:unknown[];components:unknown[];assets:number;reactBuild:{status:string}}|null}):string {
  return `<section class="export-heading"><div class="eyebrow">REVISION ${job.revision}</div><h2>Leave with the actual code.</h2><p>Both exports contain editable source. Neither embeds the original website.</p></section><div class="export-grid"><article><span class="export-symbol">&lt;/&gt;</span><h3>React + TypeScript</h3><p>Components, pages, editable content, local assets and Vite configuration.</p><code>npm install<br>npm run build</code><button data-export="react" class="primary">Download React ↓</button></article><article><span class="export-symbol">{ }</span><h3>HTML + CSS</h3><p>Standalone pages, stylesheets, assets and supported interaction adapters.</p><code>python -m http.server 8080</code><button data-export="html" class="primary">Download HTML ↓</button></article></div><div class="export-receipt"><div><h3>The evidence goes with it.</h3><p>Every archive includes its conversion report and asset provenance. ${job.report?.reactBuild.status==='passed'?'This revision’s React build is verified.':'This revision’s React production build has not been independently verified.'}</p></div><button data-export="report" class="secondary">Download report</button></div><p class="export-note">Downloads use short-lived, revision-scoped links. A new edit invalidates links to the old revision. Connect form backends and review unsupported behaviours before publishing.</p>`;
}
